services:
  - type: web
    name: iptv-privacy-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn render_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: UPDATE_INTERVAL
        value: "6"
    healthCheckPath: /status
    autoDeploy: true